### ISSUE TITLE
does ncnn part work or not

### ISSUE THREAD

**Issue by toprince** [lhwcv/DTLN_pytorch#1]
Hi,
  I've run the C++ code under deploy folder, seems it has wrong result. I'v dig into it, but haven't got any clue yet.
  not sure whether is the ncnn model (I use a tool transfer from onnx) problem.
  Please help me out, thanks!

**Comment by lhwcv** [comment]
@toprince  Hi, I already pushed third_party and models.
```
cd deploy/
sh build.sh
sh run.sh
```

**Comment by lhwcv** [comment]
@toprince  Hi, Did it solve your issue?

**Comment by lhwcv** [comment]
Already test ncnn part does work ,  Issue wil be closed
