### ISSUE TITLE
Is model.pth converted from the tensorflow pre-trained model or trained by yourself?

### ISSUE THREAD

**Issue by zuowanbushiwo** [lhwcv/DTLN_pytorch#3]
Dear sir
         Because there is no training related code in this project， So  how did this model come about? Can DTLN-aec this be ported to ncnn?
Thanks！

**Comment by zuowanbushiwo** [comment]
@lhwcv  
Can add some script about  pytorch model  or  onnx model  convert  to ncnn model ?  Thanks!

**Comment by lhwcv** [comment]
Thank you for your issue.

- I converted from TensorFlow pertained one,  we can also retrain with PyTorch. 
- DTLN-aec can also be converted to ncnn, maybe next month I'll have time to do this.
- convert script see:  [/deploy/convert_models.sh](https://github.com/lhwcv/DTLN_pytorch/blob/main/deploy/convert_models.sh)

**Comment by zuowanbushiwo** [comment]
Dear sir
   Thanks，you are so friendly .

> - I converted from TensorFlow pertained one, we can also retrain with PyTorch.    
 
 Can you also share some scripts to convert TensorFlow pertained to PyTorch model.pth file? which  tensorFlow pertained  are you using, there are  xx.h5 , xx.pb and xx.tflte  three different types of pertained files 。

and  about  DTLN-aec ,  The author only opened the pre-trained model of tflite, can this also be converted into a pytorch mode directly? then  convert  to onnx and ncnn.  Or need us to retrain with pytorch first?

Looking forward to your reply

**Comment by lhwcv** [comment]
@zuowanbushiwo 
Hi, 
- I'll share my script converted  from xx.h5 file this week
- tflite model can also be converted to PyTorch model, but I not tried.  If you have trained one, it is more convenient.

**Comment by zuowanbushiwo** [comment]
@lhwcv 
  
> - I'll share my script converted from xx.h5 file this week.  

thanks,  watching！

> -tflite model can also be converted to PyTorch model, but I not tried. If you have trained one, it is more convenient..

I'm a beginer in deep learning and the training environment has not yet been set up .  I found one [here ](https://github.com/scofir/DTLN-aec)yesterday, but the effect is not as good as the original author's.

**Comment by lhwcv** [comment]
@zuowanbushiwo 

- Convert from XX.h5 see [cvt_from_keras.py](https://github.com/lhwcv/DTLN_pytorch/blob/main/cvt_from_keras.py)
- The second point, I'll work on that next month.

**Comment by zuowanbushiwo** [comment]
@lhwcv 
 👍
