### ISSUE TITLE
为什么要转化成两个模型？

### ISSUE THREAD

**Issue by zuowanbushiwo** [lhwcv/DTLN_pytorch#4]
你好 @lhwcv 
       tensorflow 转 tensorflow lite时作者说是因为tensorflow lite 不支持复数，所以拆开成两个。
       onnx 和 ncnn也是因为不支持复数，所以被拆成两个吗？
       我在pnnx的文档看现在pytorch 转pnnx 可以支持[复数了](https://github.com/Tencent/ncnn/pull/3890)，也可以支持[torch.fft()](https://github.com/Tencent/ncnn/pull/3892) ，是不是可以直接把 pytorch 转 pnnx 再转 ncnn ，这样只有一个模型了？
       原谅我，我才刚开始学习深度学习降噪，还没有能力验证自己的想法，最近一直在看资料，想通过一些示例理解它。

谢谢！

**Comment by lhwcv** [comment]
@zuowanbushiwo 
你好， 我还没试过pnnx， 如果支持复数，并且支持torch.fft   那方便很多了。
你可以尝试PR 一下，正好强化这个能力。😄

**Comment by zuowanbushiwo** [comment]
好早啊，我会往这个方向学习的，打算专注于pytorch 和ncnn方向，最开始onnx 和 ncnn也是因为不支持复数，所以被拆成两个吗？

**Comment by lhwcv** [comment]
早上好！ 是的， 以前不支持。 后面我看下pnnx 到ncnn的 FFT 支持情况， 这样FFTW3 也可以不用引入了。

**Comment by zuowanbushiwo** [comment]
好的，谢谢您了，祝您身体健康，工作顺利，多开发关于NCNN的语音增强的例子，带领我们小辈入门 :smile:
