### ISSUE TITLE
Is there a significant difference in training results for the SeperationBlock and SeperationBlock_stateful?

### ISSUE THREAD

**Issue by c8x1** [lhwcv/DTLN_pytorch#5]
I saw that you have written two forms of SeperationBlock. The only difference between them is whether to return the hidden state out. What's the point of doing this? And which implementation has better performance? thank you for your response.

**Comment by lhwcv** [comment]
@c8x1  "hidden state out" is for realtime enhance, which process trunk  by trunk, it has better performance when in inference

**Comment by c8x1** [comment]
看到你好像是中国的，那就不用蹩脚英语了 :D. 

所以stateful的就只是用来推理的咯？

我之前也有试过把hidden传出来的训练方式，目的是把这batch的hidden state作为下一个batch的hidden state初始值，避免训练的片段比较短，实际推理又比较长的RNN泛化问题，跟这个是两回事是吧？

**Comment by lhwcv** [comment]
对的， 应该是两个问题。

**Comment by c8x1** [comment]
感谢哈，你的模型实现简洁易懂！

**Comment by lhwcv** [comment]
@c8x1  谢谢， 我们有问题再交流
