### ISSUE TITLE
有关模型部署FFT的问题

### ISSUE THREAD

**Issue by Plutoisme** [lhwcv/DTLN_pytorch#7]
作者您好，我注意到整个部署流程是将一个model拆成两个部分使用NCNN进行部署。 其中STFT层交给C++的FFTW3来实现。 但我注意到STFT的过程是分帧加窗后再加FFT，而C++的处理貌似少了加窗这一步，这一部分是否会造成一些误差呢？想听听设计代码的你是怎么考虑的。

**Comment by lhwcv** [comment]
如果实际用的时候还是要加窗的， 只是这个paper 他没加， 这里只是为了完全还原
